In [1]:
import numpy as np

In [3]:
a=np.random.randint(1,100,15)
a

array([53, 90, 71, 42, 21, 64, 26, 98, 83, 61, 12, 78, 76, 87, 15])

In [5]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[92, 31, 94, 60],
       [12, 10, 68, 49],
       [62, 49, 99, 32],
       [ 2, 72, 81, 16],
       [24, 17, 16, 67],
       [65, 77,  6, 88]])

### np.sort
- Return a sorted copy of an array

In [6]:
np.sort(a)

array([12, 15, 21, 26, 42, 53, 61, 64, 71, 76, 78, 83, 87, 90, 98])

In [10]:
np.sort(a)[::-1]

array([98, 90, 87, 83, 78, 76, 71, 64, 61, 53, 42, 26, 21, 15, 12])

In [11]:
# row
np.sort(b)

array([[31, 60, 92, 94],
       [10, 12, 49, 68],
       [32, 49, 62, 99],
       [ 2, 16, 72, 81],
       [16, 17, 24, 67],
       [ 6, 65, 77, 88]])

In [12]:
# column
np.sort(b,axis=0)

array([[ 2, 10,  6, 16],
       [12, 17, 16, 32],
       [24, 31, 68, 49],
       [62, 49, 81, 60],
       [65, 72, 94, 67],
       [92, 77, 99, 88]])

### np.append
- The numpy.append() appends values along the mentioned axis at the end of the array.

In [14]:
np.append(a,101)

array([ 53,  90,  71,  42,  21,  64,  26,  98,  83,  61,  12,  78,  76,
        87,  15, 101])

In [17]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[92., 31., 94., 60.,  1.],
       [12., 10., 68., 49.,  1.],
       [62., 49., 99., 32.,  1.],
       [ 2., 72., 81., 16.,  1.],
       [24., 17., 16., 67.,  1.],
       [65., 77.,  6., 88.,  1.]])

In [20]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[92.        , 31.        , 94.        , 60.        ,  0.97815649],
       [12.        , 10.        , 68.        , 49.        ,  0.11299222],
       [62.        , 49.        , 99.        , 32.        ,  0.77296928],
       [ 2.        , 72.        , 81.        , 16.        ,  0.42437867],
       [24.        , 17.        , 16.        , 67.        ,  0.41698892],
       [65.        , 77.        ,  6.        , 88.        ,  0.82693769]])

### np.concatenate
- numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [23]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [25]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique
- with the help of np.unique() method,we can get the unique values from an array given as parameter in np.unique() method.

In [27]:
a=np.array([1,1,1,2,2,2,2,2,3,3,3,4,4,4,4,5,5,5,6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims
- with the help of numpy.expand_dims() method,we can get the expanded dimensions of an array

In [29]:
a=np.random.randint(1,100,15)
a.shape

(15,)

In [32]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [35]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where
- The numpy.where() function return the indices of elements in an input array where the given condition is satisfied.

In [37]:
# np.where(condition,True,False)

In [38]:
a

array([30, 87, 64, 53, 88, 17, 75, 48, 32, 62, 44, 76, 96,  5, 37])

In [40]:
np.where(a<50)

(array([ 0,  5,  7,  8, 10, 13, 14], dtype=int64),)

In [42]:
np.where(a>50)

(array([ 1,  2,  3,  4,  6,  9, 11, 12], dtype=int64),)

In [43]:
np.where(a>50,0,a)

array([30,  0,  0,  0,  0, 17,  0, 48, 32,  0, 44,  0,  0,  5, 37])

In [44]:
np.where(a%2==0,0,a)

array([ 0, 87,  0, 53,  0, 17, 75,  0,  0,  0,  0,  0,  0,  5, 37])

### np.argmax & np.argmin
- The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [58]:
# np.argmax
a

array([30, 87, 64, 53, 88, 17, 75, 48, 32, 62, 44, 76, 96,  5, 37])

In [52]:
np.argmax(a)

12

In [53]:
b

array([[92, 31, 94, 60],
       [12, 10, 68, 49],
       [62, 49, 99, 32],
       [ 2, 72, 81, 16],
       [24, 17, 16, 67],
       [65, 77,  6, 88]])

In [54]:
# columns
np.argmax(b,axis=0)

array([0, 5, 2, 5], dtype=int64)

In [55]:
# rows
np.argmax(b,axis=1)

array([2, 2, 2, 2, 3, 3], dtype=int64)

In [56]:
a

array([30, 87, 64, 53, 88, 17, 75, 48, 32, 62, 44, 76, 96,  5, 37])

In [59]:
# np.argmin
np.argmin(a)

13

In [60]:
np.argmin(b,axis=0)

array([3, 1, 5, 3], dtype=int64)

In [61]:
np.argmin(b,axis=1)

array([1, 1, 3, 0, 2, 2], dtype=int64)

### np.cumsum
- numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given lists.

In [2]:
import numpy as np
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [3]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15])

In [78]:
b

array([[92, 31, 94, 60],
       [12, 10, 68, 49],
       [62, 49, 99, 32],
       [ 2, 72, 81, 16],
       [24, 17, 16, 67],
       [65, 77,  6, 88]])

In [79]:
np.cumsum(b)

array([  92,  123,  217,  277,  289,  299,  367,  416,  478,  527,  626,
        658,  660,  732,  813,  829,  853,  870,  886,  953, 1018, 1095,
       1101, 1189])

In [80]:
np.cumsum(b,axis=0)

array([[ 92,  31,  94,  60],
       [104,  41, 162, 109],
       [166,  90, 261, 141],
       [168, 162, 342, 157],
       [192, 179, 358, 224],
       [257, 256, 364, 312]])

In [81]:
np.cumsum(b,axis=1)

array([[ 92, 123, 217, 277],
       [ 12,  22,  90, 139],
       [ 62, 111, 210, 242],
       [  2,  74, 155, 171],
       [ 24,  41,  57, 124],
       [ 65, 142, 148, 236]])

### np.cumprod

In [82]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [83]:
np.cumprod(a)

array([  1,   2,   6,  24, 120])

### np.percentile
- numpy.percentile() function used to compute the nth percentile of the given data(array elements)along the specified axis.

In [85]:
a=np.random.randint(1,100,15)
a

array([96,  1, 88,  5, 98, 10, 82, 76, 53,  8, 89, 82, 53, 49, 37])

In [87]:
np.percentile(a,100)

98.0

In [88]:
np.percentile(a,0)

1.0

In [89]:
np.percentile(a,50)

53.0

In [90]:
np.median(a)

53.0

### np.histogram
- Numpy has a built in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [91]:
a

array([96,  1, 88,  5, 98, 10, 82, 76, 53,  8, 89, 82, 53, 49, 37])

In [92]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 1, 0, 1, 1, 2, 0, 1, 4, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [93]:
np.histogram(a,bins=[0,50,100])

(array([6, 9], dtype=int64), array([  0,  50, 100]))

### np.corrcoef
- Return person product moment correlation coefficients.

In [2]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin
- with the help of numpy.isin() method,we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [4]:
a=np.random.randint(1,100,15)
a

array([25, 40, 11, 22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

In [6]:
items=[10,20,30,40,50,60,70,80,90,100]

In [7]:
np.isin(a,items)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [8]:
a[np.isin(a,items)]

array([40])

### np.flip
- The numpy.flip() function reverses the order of array elements along the specified axis,preserving the shape of the array.

In [9]:
a

array([25, 40, 11, 22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

In [10]:
np.flip(a)

array([56, 39, 48, 37, 12, 39, 48, 59, 61, 96,  8, 22, 11, 40, 25])

In [11]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[73, 57, 66, 59],
       [87, 71, 15, 86],
       [25, 49, 37, 72],
       [56, 63,  3, 42],
       [49, 50, 86, 99],
       [62, 42, 30, 85]])

In [12]:
np.flip(b)

array([[85, 30, 42, 62],
       [99, 86, 50, 49],
       [42,  3, 63, 56],
       [72, 37, 49, 25],
       [86, 15, 71, 87],
       [59, 66, 57, 73]])

In [13]:
np.flip(b,axis=0)

array([[62, 42, 30, 85],
       [49, 50, 86, 99],
       [56, 63,  3, 42],
       [25, 49, 37, 72],
       [87, 71, 15, 86],
       [73, 57, 66, 59]])

In [14]:
np.flip(b,axis=1)

array([[59, 66, 57, 73],
       [86, 15, 71, 87],
       [72, 37, 49, 25],
       [42,  3, 63, 56],
       [99, 86, 50, 49],
       [85, 30, 42, 62]])

### np.put
- The numpy.put() function replaces specific elements of an array with given values of p_array.Array indexed works on flatted array.

In [15]:
a

array([25, 40, 11, 22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

In [20]:
np.put(a,[0,1],[1,2]) # (array,list of index,list of values) permanent operation

In [21]:
a

array([ 1,  2, 11, 22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

### np.delete 
- The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [22]:
a

array([ 1,  2, 11, 22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

In [25]:
np.delete(a,0) #(array,index)

array([ 2, 11, 22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

In [27]:
a

array([ 1,  2, 11, 22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

In [29]:
np.delete(a,[0,1,2])  #(array,list of index)

array([22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

## set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [30]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

In [31]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
np.intersect1d(m,n)

array([3, 4, 5])

In [34]:
np.setdiff1d(m,n)

array([1, 2])

In [35]:
np.setdiff1d(n,m)

array([6, 7])

In [36]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [43]:
np.in1d(m,1)  #(array,value)

array([ True, False, False, False, False])

In [39]:
m[np.in1d(m,1)]

array([1])

In [44]:
np.in1d(n,5)  #(array,value)

array([False, False,  True, False, False])

In [45]:
n[np.in1d(n,5)]

array([5])

### np.clip
- numpy.clip() function is used to clip(limit) the values in an array.

In [46]:
a

array([ 1,  2, 11, 22,  8, 96, 61, 59, 48, 39, 12, 37, 48, 39, 56])

In [48]:
np.clip(a,a_min=25,a_max=75) #(all values between the lower and upper boundary)

array([25, 25, 25, 25, 25, 75, 61, 59, 48, 39, 25, 37, 48, 39, 56])