### What is numpy?
- Numpy created because of python data type are very slow but python language is easy to learn.
- Numpy build in c language and integrated with python language.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences(List)

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
# vector
# np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# matrix
# 2D and 3D
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [4]:
# tensor
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [7]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [33]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [35]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# 4D
x=np.arange(16).reshape(2,2,2,2)
x

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [36]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
np.arange(0,50,2).reshape(5,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [38]:
# np.ones (for initializing array)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# np.zeros (for initializing array)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
# np.random (for initializing array)
np.random.random((3,5))

array([[0.1624412 , 0.90870389, 0.01213674, 0.98796902, 0.15602026],
       [0.09679604, 0.60862308, 0.20052027, 0.22859874, 0.53737662],
       [0.13698358, 0.15210556, 0.40054231, 0.05776574, 0.85749144]])

In [8]:
# np.linspace
np.linspace(-10,10,5) #(lower boundary,upper boundary,no of items)

array([-10.,  -5.,   0.,   5.,  10.])

In [45]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [48]:
# np.identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Array Attributes

In [11]:
# 1D
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 2D
a2=np.arange(16).reshape(4,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
# 3D
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [60]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(4, 4)
(2, 2, 2)


In [61]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

10
16
8


In [72]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
4
4


In [76]:
a=np.arange(11,dtype=np.int32)
print(a.itemsize)
print(a)

4
[ 0  1  2  3  4  5  6  7  8  9 10]


In [77]:
b=np.arange(11,dtype=np.int64)
print(b.itemsize)
print(b)

8
[ 0  1  2  3  4  5  6  7  8  9 10]


In [80]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


### Changing Datatype

In [87]:
# astype
a=np.arange(10,dtype=np.int64)
print(a.dtype)

a=a.astype(np.int32)
print(a.dtype)

int64
int32


### Array Operations

In [90]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [91]:
# scalar operation
# arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [92]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [93]:
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [94]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [95]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [96]:
a1//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [97]:
a1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [100]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [101]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [102]:
# vector operations
# arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [103]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [104]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [105]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [106]:
a1//a2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [107]:
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

In [109]:
a1 % a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Array Functions

In [5]:
a1=np.random.random((3,3))
print(a1)
print()
a1=np.round(a1*100)
print(a1)

[[0.12811782 0.73255183 0.45955241]
 [0.83184399 0.07095521 0.11122347]
 [0.55411484 0.9264563  0.74962198]]

[[13. 73. 46.]
 [83.  7. 11.]
 [55. 93. 75.]]


In [27]:
# max/min/sum/prod
print(np.min(a1))
print(np.max(a1))
print(np.sum(a1))
print(np.prod(a1))

36.0
99.0
647.0
3.24142971424272e+16


In [29]:
# 0 -> columns and 1 -> rows
print(np.max(a1,axis=1))

[99. 97. 91.]


In [30]:
print(np.max(a1,axis=0))

[81. 99. 97.]


In [31]:
print(np.min(a1,axis=1))

[55. 36. 59.]


In [32]:
print(np.min(a1,axis=0))

[36. 49. 59.]


In [33]:
print(np.sum(a1,axis=1))

[234. 182. 231.]


In [34]:
print(np.sum(a1,axis=0))

[172. 239. 236.]


In [35]:
print(np.prod(a1,axis=1))

[435600. 171108. 434889.]


In [36]:
print(np.prod(a1,axis=0))

[160380. 441441. 457840.]


In [39]:
# mean/median/std/var
print(np.mean(a1))
print(np.mean(a1,axis=1))
print(np.mean(a1,axis=0))

71.88888888888889
[78.         60.66666667 77.        ]
[57.33333333 79.66666667 78.66666667]


In [42]:
print(np.median(a1))
print(np.median(a1,axis=1))
print(np.median(a1,axis=0))

80.0
[80. 49. 81.]
[55. 91. 80.]


In [44]:
print(np.std(a1))
print(np.std(a1,axis=1))
print(np.std(a1,axis=0))

21.455092347839496
[18.018509   26.23398983 13.3666251 ]
[18.44511378 21.92917894 15.54205764]


In [46]:
print(np.var(a1))
print(np.var(a1,axis=1))
print(np.var(a1,axis=0))

460.32098765432096
[324.66666667 688.22222222 178.66666667]
[340.22222222 480.88888889 241.55555556]


In [47]:
# trigonometric functions
np.sin(a1)

array([[-0.99975517, -0.99920683, -0.99388865],
       [-0.99177885, -0.95375265,  0.37960774],
       [-0.62988799,  0.10598751,  0.63673801]])

In [51]:
# dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

print(a2)
print()
print(a3)
print()

print(np.dot(a2,a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [55]:
# log and exp
np.log(a1)

array([[4.00733319, 4.59511985, 4.38202663],
       [3.58351894, 3.8918203 , 4.57471098],
       [4.39444915, 4.51085951, 4.07753744]])

In [56]:
np.exp(a1)

array([[7.69478527e+23, 9.88903032e+42, 5.54062238e+34],
       [4.31123155e+15, 1.90734657e+21, 1.33833472e+42],
       [1.50609731e+35, 3.31740010e+39, 4.20121040e+25]])

In [6]:
# round/floor/ceil
np.round(np.random.random((3,4))*100,2)

array([[69.55, 31.54, 29.6 , 76.19],
       [95.53, 76.64, 41.72, 58.46],
       [70.87, 59.76, 93.52, 25.24]])

In [64]:
np.floor(np.random.random((3,4))*100)

array([[ 6., 91., 80., 85.],
       [ 1., 50., 74.,  8.],
       [17., 13., 58., 96.]])

In [65]:
np.ceil(np.random.random((3,4))*100)

array([[87., 85., 95.,  8.],
       [ 6., 77.,  9., 99.],
       [35., 18., 49., 69.]])

### # indexing and slicing

In [83]:
# indexing
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [71]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a1[-1]

9

In [73]:
a1[0]

0

In [74]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
a2[1,2]

6

In [76]:
a2[0,2]

2

In [77]:
a2[2,3]

11

In [78]:
a2[1,0]

4

In [79]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [80]:
a3[1,0,1]

5

In [81]:
a3[0,1,0]

2

In [82]:
a3[0,0,0]

0

In [91]:
# slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a1[0:3]

array([0, 1, 2])

In [85]:
a1[2:5]

array([2, 3, 4])

In [86]:
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [88]:
a1[0:9:2]

array([0, 2, 4, 6, 8])

In [93]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
a2[0,:]

array([0, 1, 2, 3])

In [94]:
a2[:,2]

array([ 2,  6, 10])

In [97]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [103]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [107]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [114]:
a2[1,::3]

array([4, 7])

In [118]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [121]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [124]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
a3[0,1,:]

array([3, 4, 5])

In [128]:
a3[1,:,1]

array([10, 13, 16])

In [130]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [142]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [144]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [145]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [146]:
a3

for i in a3:
    print(i,"\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[18 19 20]
 [21 22 23]
 [24 25 26]] 



In [147]:
a2

for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [148]:
a3 

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [149]:
# reshape

In [153]:
# transpose
print(np.transpose(a2))
print()
print(a2.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [158]:
# ravel (convert 2D,3D into 1D array)
print(a2.ravel())
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### Stacking

In [162]:
# horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [166]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [172]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [173]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [174]:
np.vstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [178]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [180]:
np.hsplit(a4,2) #(array,no of parts)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [181]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [182]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [185]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]