In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [21]:
# np.empty(no of items) -create empty np.array of given size. 
a=np.empty(10,dtype=np.int8)
print(a)
a=a*np.nan
print(a)
a[4]=1
print(a)

[0 0 0 0 0 0 0 0 0 0]
[nan nan nan nan nan nan nan nan nan nan]
[nan nan nan nan  1. nan nan nan nan nan]


In [22]:
# Filling the numpy array with NaN values
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
x=int(input('Enter Num1: '))
y=int(input('Enter Num2: '))

random_arr=np.random.random((x,y))
random_arr_sum=np.sum(random_arr)
total_item=random_arr.size

print()
print(random_arr)
print()
print(total_item)
print()
print(random_arr_sum)
print()
print('Avg: ',random_arr_sum/total_item)
print()
print(random_arr.mean())

Enter Num1: 5
Enter Num2: 5

[[0.8131918  0.80813333 0.73458951 0.8524603  0.78570209]
 [0.12172938 0.74688383 0.07722567 0.39935195 0.06468476]
 [0.8500267  0.38503957 0.37561476 0.1599382  0.46976195]
 [0.20424014 0.78181916 0.81803278 0.24636516 0.83016362]
 [0.65714037 0.97549204 0.04292177 0.88160683 0.05869256]]

25

13.14080823407137

Avg:  0.5256323293628548

0.5256323293628548


In [47]:
a,b = map(int, input("Enter two numbers: ").split())
x = np.random.random((a,b))
print(x)
print(x.mean())

Enter two numbers: 5 5
[[0.21805813 0.98338495 0.82595639 0.92738075 0.27270317]
 [0.67496844 0.85153342 0.3700961  0.79565317 0.67833644]
 [0.9142071  0.67978106 0.86982594 0.72579053 0.74643149]
 [0.49285959 0.00495729 0.34987128 0.47724619 0.28974497]
 [0.34807681 0.1311056  0.7149016  0.97866668 0.85772483]]
0.6071704765826931


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [137]:
import sys

def border_arr():
    x=int(input('Enter Num1: '))
    y=int(input('Enter Num2: '))

    empty=np.zeros((x,y),dtype=np.int32)

    print()
    print(empty)

    empty[0:x:x-1]=1
    empty[1:x-1,0:y:y-1]=1

    print()
    print(empty)
    
    return sys.getsizeof(empty)
    
    
border_arr()

Enter Num1: 5
Enter Num2: 5

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


228

In [136]:
import sys

def borderArray(a,b):
    x = np.ones((a,b))
    x[1:-1, 1:-1] = 0    # Except the border, changing all other elements to 0
    return x,sys.getsizeof(x)  # 288


borderArray(4,5)

(array([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]]),
 288)

In [135]:
import sys

def borderArray(a,b):
    x = np.ones((a,b),dtype=np.int32)
    x[1:-1, 1:-1] = 0    # Except the border, changing all other elements to 0
    return x,sys.getsizeof(x) #208

borderArray(4,5)

(array([[1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]]),
 208)

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [154]:
np.linspace(0,1,12)[1:-1] # excluded

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [156]:
np.linspace(0,1,10)  # included

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [170]:
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

#Identy matrix of size 3-- 3X3
np.eye(3)

#Identy matrix of size 4-- 4X4
np.identity(4)

# eye and identity are same.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [176]:
x=np.zeros((5,5),dtype=int)
x[:,1]=1
x[:,2]=2
x[:,3]=3
x[:,4]=4
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [179]:
z = np.zeros((5,5))
z=z+np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [183]:
a = np.random.randint(1, 100, (10, 2))
p = np.array([2,3])
np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)

array([ 83,  21,  94,  71,  69,  26,  71, 108, 118,  53])

In [184]:
a

array([[29, 82],
       [21, 13],
       [77, 60],
       [20, 72],
       [32, 66],
       [17, 25],
       [71, 22],
       [80, 79],
       [98, 73],
       [23, 52]])

In [185]:
p

array([2, 3])

In [186]:
(a-p)**2

array([[ 729, 6241],
       [ 361,  100],
       [5625, 3249],
       [ 324, 4761],
       [ 900, 3969],
       [ 225,  484],
       [4761,  361],
       [6084, 5776],
       [9216, 4900],
       [ 441, 2401]])

In [187]:
np.sum((a-p)**2, axis=1)

array([ 6970,   461,  8874,  5085,  4869,   709,  5122, 11860, 14116,
        2842])

In [188]:
np.sqrt(np.sum((a-p)**2, axis=1))

array([ 83.48652586,  21.47091055,  94.20191081,  71.30918594,
        69.7782201 ,  26.62705391,  71.56814934, 108.90362712,
       118.81077392,  53.31041174])

In [194]:
np.random.randint(1,100,(5,5))

array([[86, 29, 67, 85, 38],
       [32, 53, 88, 64, 35],
       [88, 57, 45, 59, 39],
       [60, 28, 71, 60, 75],
       [41, 76, 57, 77,  6]])

In [196]:
np.random.randint(1,100,(2,5,5))

array([[[50, 88, 86,  2, 33],
        [30, 15,  8, 67, 89],
        [34, 65, 64, 82, 56],
        [ 6, 56, 69, 58, 18],
        [88, 76, 95, 97, 91]],

       [[70, 87, 47, 74,  8],
        [54, 98, 46,  6, 63],
        [ 5, 97, 45,  8, 14],
        [56, 22, 16, 49, 79],
        [33, 36, 40, 99, 75]]])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [199]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```


In [17]:
a = input().strip().split()
np.array(a[::-1], dtype=np.float32)

1 2 3 4 5 


array([5., 4., 3., 2., 1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.

**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [38]:
count=0
a=np.array([])

if a.size==0:
    print('Elements_count: ',0)
else:
    for i in np.nditer(a):
        count+=1
    print('Elements_count: ',count)

Elements_count:  0


In [41]:
a=np.array([])

if a.size==0:
    print('elements_count: ',0)
else:
    print('elements_count: ',a.size)

elements_count:  0


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function


**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [44]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [49]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
    return np.vstack(args)


a = np.arange(10).reshape(2, -1)
print("a=",a)
print()

b = np.repeat(1, 10).reshape(2, -1)
print("b=",b)
print()

print(vertical_stack(a,b))
print()

c = np.random.random((2,5))
print("c=", c)
print()
print(vertical_stack(a,b,c))

a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.49927837 0.06024056 0.33212401 0.25564179 0.16220498]
 [0.51410682 0.08918618 0.39598031 0.86133231 0.06236152]]

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.49927837 0.06024056 0.33212401 0.25564179 0.16220498]
 [0.51410682 0.08918618 0.39598031 0.86133231 0.06236152]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.

**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [50]:
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError
        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1
    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end 


date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

### `Q-14:` Subtract the mean of each row from a matrix.

In [51]:
x = np.random.random((5,4))
x - x.mean(axis = 1, keepdims = True)

array([[-0.11577397,  0.02584442,  0.31238455, -0.222455  ],
       [-0.24995241,  0.14887074, -0.0042941 ,  0.10537577],
       [-0.06876239,  0.24584495,  0.17622305, -0.35330561],
       [ 0.11291258, -0.07963448,  0.20800566, -0.24128375],
       [-0.15707793,  0.41877048, -0.23083754, -0.03085501]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [53]:
a = np.arange(9).reshape(3,3)
print(a)
print()
a[:, [0, 2, 1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]



array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### `Q-16:` Replace odd elements in arrays with -1.

In [54]:
a = np.arange(10)
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [55]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [56]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3848, 9880, 3048, 1447, 1438],
       [8663, 6161, 8188, 8996,   75],
       [8627, 1858, 7065, 4323,  903],
       [1378, 3688, 7324, 8535, 8189],
       [9558, 1351, 7338, 6996, 4249],
       [6223, 8466,  987, 4527, 7617],
       [4518, 1796, 1614, 8855, 3802],
       [9366, 4100,  629, 3465, 8253]])

In [57]:
arr1[:, ::2]

array([[3848, 3048, 1438],
       [8663, 8188,   75],
       [8627, 7065,  903],
       [1378, 7324, 8189],
       [9558, 7338, 4249],
       [6223,  987, 7617],
       [4518, 1614, 3802],
       [9366,  629, 8253]])

In [58]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.38480367, 1.        , 0.30321265, 0.13992861, 0.13901071],
       [0.87587965, 0.62070372, 0.82743498, 0.90984192, 0.        ],
       [0.87220806, 0.181846  , 0.71290158, 0.43324834, 0.08444671],
       [0.13289138, 0.36848547, 0.73931668, 0.86282509, 0.82753697],
       [0.96715961, 0.13013768, 0.74074452, 0.70586435, 0.42570117],
       [0.62702703, 0.85578786, 0.09301377, 0.45405405, 0.76919939],
       [0.45313616, 0.17552269, 0.15696073, 0.8954615 , 0.38011219],
       [0.94757777, 0.41050484, 0.05650178, 0.34574197, 0.83406425]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [59]:
#Code here
def nthmax(arr, n):
    if n>len(arr):
        raise IndexError("n is way out of limit")
    arr.sort()
    return arr[-n]
nthmax(np.array([12,34,40,7,1,0]),2)

34

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [60]:
#code here
a = np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])